# Generated by Django 6.0.1 on 2026-03-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
