# Generated by Django 6.0.1 on 2026-02-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tracking_start_date',
            field=models.DateField(blank=True, help_text='Anchor date for weekly tracking intervals (set on first child creation).', null=True),
        ),
    ]
