# Generated by Django 6.0.1 on 2026-01-17 09:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WellbeingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. A1, A2... A10",
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^A([1-9]|10)$", "Code must be A1..A10"
                            )
                        ],
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("communication", "Communication"),
                            ("routines", "Routines"),
                            ("emotional_responses", "Emotional Responses"),
                            ("sensory_behaviors", "Sensory Behaviors"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                ("order", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyWellbeingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(help_text="Monday of the week")),
                ("week_end", models.DateField(help_text="Sunday of the week")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted")],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("communication_score", models.FloatField(blank=True, null=True)),
                ("routines_score", models.FloatField(blank=True, null=True)),
                ("emotional_score", models.FloatField(blank=True, null=True)),
                ("sensory_score", models.FloatField(blank=True, null=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_entries",
                        to="wellbeing.childprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Weekly Wellbeing Entries",
            },
        ),
        migrations.CreateModel(
            name="WeeklyWellbeingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slider_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0-4 scale",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "binary_flag",
                    models.IntegerField(
                        blank=True,
                        help_text="Derived: 1 if slider <= 1 (Risk), else 0",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="wellbeing.weeklywellbeingentry",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wellbeing.wellbeingquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CaregiverChild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caregiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver_relationships",
                        to="wellbeing.childprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("caregiver", "child"), name="unique_caregiver_child"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="weeklywellbeingentry",
            index=models.Index(
                fields=["child", "-week_start"], name="wellbeing_w_child_i_35e498_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklywellbeingentry",
            index=models.Index(
                fields=["caregiver", "-week_start"],
                name="wellbeing_w_caregiv_8b7999_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklywellbeingentry",
            constraint=models.UniqueConstraint(
                fields=("caregiver", "child", "week_start"), name="unique_weekly_entry"
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklywellbeinganswer",
            constraint=models.UniqueConstraint(
                fields=("entry", "question"), name="unique_entry_question"
            ),
        ),
    ]
