# Generated by Django 6.0.1 on 2026-01-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wellbeing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childprofile",
            name="family_asd",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="jaundice",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="childprofile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("m", "Male"), ("f", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
