# Generated by Django 6.0.1 on 2026-02-21 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0002_childprofile_family_asd_childprofile_jaundice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_label', models.CharField(default='Model not trained yet', max_length=255)),
                ('prediction_score', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='stub-v1', max_length=50)),
                ('explanation_json', models.JSONField(blank=True, null=True)),
                ('narrative_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_results', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_results', to='wellbeing.childprofile')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='wellbeing.weeklywellbeingentry')),
            ],
        ),
    ]
