# Generated by Django 6.0.1 on 2026-04-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0003_predictionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='child_profiles/'),
        ),
    ]
