# Generated by Django 6.0.1 on 2026-03-22 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

def seed_games(apps, schema_editor):
    TherapyGame = apps.get_model('games', 'TherapyGame')
    games = [
        {
            'title': 'Emotion Match',
            'slug': 'emotion-match',
            'goal': 'Identify and match core emotions',
            'age_range': '4–10',
            'description': 'A fun matching game to help children recognize and label different facial expressions and their corresponding emotions.',
            'embed_url': '',
        },
        {
            'title': 'Routine Builder',
            'slug': 'routine-builder',
            'goal': 'Build a visual schedule for the day',
            'age_range': '6–12',
            'description': 'An interactive activity where caregivers and children can arrange daily tasks into a manageable visual sequence.',
            'embed_url': '',
        }
    ]
    for game_data in games:
        TherapyGame.objects.create(**game_data)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_games),
    ]
