# Generated by Django 6.0.1 on 2026-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_seed_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapygame',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='therapygame',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
