# Generated by Django 6.0.1 on 2026-03-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_therapygame_provider_name_therapygame_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapygame',
            name='embed_type',
            field=models.CharField(choices=[('URL', 'Remote URL'), ('LOCAL', 'Local HTML Package')], default='URL', max_length=10),
        ),
        migrations.AddField(
            model_name='therapygame',
            name='h5p_file_path',
            field=models.CharField(blank=True, help_text='Path relative to static/, e.g., h5p_packages/emotion-match.h5p', max_length=255),
        ),
        migrations.AddField(
            model_name='therapygame',
            name='local_embed_path',
            field=models.CharField(blank=True, help_text='Path relative to static/, e.g., h5p/emotion-match/index.html', max_length=255),
        ),
    ]
